# Generated by Django 4.1 on 2022-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_participant_meetup_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='Participant',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.participant'),
        ),
    ]
