# Generated by Django 4.1 on 2022-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-07-22'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organiser_email',
            field=models.EmailField(default='etst@gamil.com', max_length=254),
            preserve_default=False,
        ),
    ]
