# Generated by Django 4.1 on 2022-10-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_date_meetup_organiser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='Participant',
            new_name='participants',
        ),
    ]
